"""add board model

Revision ID: 20e7ee05048f
Revises: 4f23d56e1c04
Create Date: 2018-12-08 16:49:58.387143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e7ee05048f'
down_revision = '4f23d56e1c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('seat_num', sa.Integer(), nullable=True),
    sa.Column('qr_code', sa.String(length=128), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boards')
    # ### end Alembic commands ###
